# Generated by Django 4.0.6 on 2022-07-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocksItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package_count', models.FloatField()),
                ('countainer_count', models.FloatField()),
                ('pause_count', models.FloatField()),
                ('empty_trailzer', models.CharField(max_length=200)),
            ],
        ),
    ]
