# Generated by Django 4.0.6 on 2022-07-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kautus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docksitem',
            name='empty_trailzer',
        ),
        migrations.AddField(
            model_name='docksitem',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docksitem',
            name='person_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
