# Generated by Django 4.0.6 on 2022-07-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kautus', '0002_remove_docksitem_empty_trailzer_docksitem_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocksItems',
        ),
        migrations.AddField(
            model_name='docksitem',
            name='empty_trailzer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
